# Generated by Django 3.2.13 on 2022-04-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='klub',
            fields=[
                ('kode_klub', models.AutoField(primary_key=True, serialize=False)),
                ('nama_klub', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=255)),
                ('logo_klub', models.CharField(max_length=255)),
                ('status_klub', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('kode_pemain', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pemain', models.CharField(max_length=70)),
                ('tgl_lahir', models.DateField()),
                ('foto', models.CharField(max_length=255)),
                ('no_punggung', models.CharField(max_length=2)),
                ('posisi', models.CharField(max_length=30)),
                ('kode_klub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kode_klub+', to='main.klub')),
            ],
        ),
    ]
