# Generated by Django 3.2.13 on 2022-04-24 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='liga',
            fields=[
                ('kode_liga', models.AutoField(primary_key=True, serialize=False)),
                ('nama_liga', models.CharField(max_length=100)),
                ('negara', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='matchday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.SmallIntegerField()),
                ('away_score', models.SmallIntegerField()),
                ('tgl_pertandingan', models.DateField()),
                ('status', models.CharField(max_length=1)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kode_klub+', to='main.klub')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kode_klub+', to='main.klub')),
                ('kode_liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kode_liga+', to='main.liga')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kode_klub+', to='main.klub')),
            ],
        ),
    ]
